 --[[ 
 columnia.register_all   (
	mat, 
	desc, 
	image, 
	groups, 
	craft, 
	sounds
	)
	--]]

columnia.register_all("default:sandstone")
columnia.register_all("default:sandstonebrick")
columnia.register_all("default:cobble")
columnia.register_all("default:cobble_baked")
columnia.register_all("default:stone")
columnia.register_all("default:cactus", nil, "default_cactus_side.png")
columnia.register_all("default:cactus_block")
columnia.register_all("default:cactus_brick")
columnia.register_all("default:stone_baked")
columnia.register_all("default:stonebrick_baked")
columnia.register_all("default:mossycobble")
columnia.register_all("default:obsidian")
columnia.register_all("default:obsidianbrick")
columnia.register_all("default:sandstonebrick")
columnia.register_all("default:stonebrick")

columnia.register_all("default:wood", "Common Wood")
columnia.register_all("default:junglewood", "Jungle Wood")
columnia.register_all("default:palewood", "Pale Wood")
columnia.register_all("default:birchwood", "Birch Wood")
columnia.register_all("default:colwood_black", "Black Wood")
columnia.register_all("default:colwood_blue", "Blue Wood")
columnia.register_all("default:colwood_brown", "Brown Wood")
columnia.register_all("default:colwood_cyan", "Cyan Wood")
columnia.register_all("default:colwood_dark_green", "Dark Green Wood")
columnia.register_all("default:colwood_dark_grey", "Dark Grey Wood")
columnia.register_all("default:colwood_grey", "Grey Wood")
columnia.register_all("default:colwood_green", "Green Wood")
columnia.register_all("default:colwood_magenta", "Magenta Wood")
columnia.register_all("default:colwood_orange", "Orange Wood")
columnia.register_all("default:colwood_pink", "Pink Wood")
columnia.register_all("default:colwood_red", "Red Wood")
columnia.register_all("default:colwood_violet", "Violet Wood")
columnia.register_all("default:colwood_white", "White Wood")
columnia.register_all("default:colwood_yellow", "Yellow Wood")

columnia.register_all("default:bark")
columnia.register_all("default:jungle_bark")
columnia.register_all("default:pale_bark")
columnia.register_all("default:birch_bark")

columnia.register_all("default:brick", "Brick")
columnia.register_all("default:brick_black", "Black Brick")
columnia.register_all("default:brick_blue", "Blue Brick")
columnia.register_all("default:brick_brown", "Brown Brick")
columnia.register_all("default:brick_cyan", "Cyan Brick")
columnia.register_all("default:brick_dark_green", "Dark Green Brick")
columnia.register_all("default:brick_dark_grey", "Grey Brick")
columnia.register_all("default:brick_green", "Green Brick")
columnia.register_all("default:brick_grey", "Grey Brick")
columnia.register_all("default:brick_magenta", "Magenta Brick")
columnia.register_all("default:brick_orange", "Orange Brick")
columnia.register_all("default:brick_pink", "Pink Brick")
columnia.register_all("default:brick_red", "Red Brick")
columnia.register_all("default:brick_violet", "Violet Brick")
columnia.register_all("default:brick_white", "White Brick")
columnia.register_all("default:brick_yellow", "Yellow Brick")

columnia.register_all("default:marble_brick")
columnia.register_all("default:marble")
columnia.register_all("default:chondrite")
columnia.register_all("default:chondrite_brick")
columnia.register_all("default:tuff")
columnia.register_all("default:tuff_brick")
columnia.register_all("default:tuff_baked")
columnia.register_all("default:tuff_baked_brick")
columnia.register_all("default:essexite")
columnia.register_all("default:essexite_brick")

columnia.register_all("columnia:rusty_block")
