local S = minetest.get_translator("columnia")
 
--[[ 
 columnia.register_all   (
	mat, 
	desc, 
	image, 
	groups, 
	craft, 
	sounds
	)
	--]]

columnia.register_all("hades_core:sandstone")
columnia.register_all("hades_core:sandstonebrick")
columnia.register_all("hades_core:cobble")
columnia.register_all("hades_core:cobble_baked")
columnia.register_all("hades_core:stone")
columnia.register_all("hades_core:cactus_brick")
columnia.register_all("hades_core:stone_baked")
columnia.register_all("hades_core:stonebrick_baked")
columnia.register_all("hades_core:mossycobble")
columnia.register_all("hades_core:obsidian")
columnia.register_all("hades_core:obsidianbrick")
columnia.register_all("hades_core:sandstonebrick")
columnia.register_all("hades_core:stonebrick")

columnia.register_all("hades_trees:wood", S("Temperate Wood"))
columnia.register_all("hades_trees:jungle_wood", S("Tropical Wood"))
columnia.register_all("hades_trees:pale_wood", S("Pale Wood"))
columnia.register_all("hades_trees:cream_wood", S("Cream Wood"))
columnia.register_all("hades_trees:lush_wood", S("Lush Wood"))
columnia.register_all("hades_trees:colwood_uncolored", S("Uncolored Canvas Wood"))
columnia.register_all("hades_trees:colwood_black", S("Black Canvas Wood"))
columnia.register_all("hades_trees:colwood_blue", S("Blue Canvas Wood"))
columnia.register_all("hades_trees:colwood_brown", S("Brown Canvas Wood"))
columnia.register_all("hades_trees:colwood_cyan", S("Cyan Canvas Wood"))
columnia.register_all("hades_trees:colwood_dark_green", S("Dark Green Canvas Wood"))
columnia.register_all("hades_trees:colwood_dark_grey", S("Dark Grey Canvas Wood"))
columnia.register_all("hades_trees:colwood_grey", S("Grey Canvas Wood"))
columnia.register_all("hades_trees:colwood_green", S("Green Canvas Wood"))
columnia.register_all("hades_trees:colwood_magenta", S("Magenta Canvas Wood"))
columnia.register_all("hades_trees:colwood_orange", S("Orange Canvas Wood"))
columnia.register_all("hades_trees:colwood_pink", S("Pink Canvas Wood"))
columnia.register_all("hades_trees:colwood_red", S("Red Canvas Wood"))
columnia.register_all("hades_trees:colwood_violet", S("Violet Canvas Wood"))
columnia.register_all("hades_trees:colwood_white", S("White Canvas Wood"))
columnia.register_all("hades_trees:colwood_yellow", S("Yellow Canvas Wood"))

columnia.register_all("hades_trees:bark")
columnia.register_all("hades_trees:jungle_bark")
columnia.register_all("hades_trees:pale_bark")
columnia.register_all("hades_trees:birch_bark")
columnia.register_all("hades_trees:lush_bark")
columnia.register_all("hades_trees:canvas_bark")

columnia.register_all("hades_core:brick", S("Brick"))
columnia.register_all("hades_core:brick_black", S("Black Brick"))
columnia.register_all("hades_core:brick_blue", S("Blue Brick"))
columnia.register_all("hades_core:brick_brown", S("Brown Brick"))
columnia.register_all("hades_core:brick_cyan", S("Cyan Brick"))
columnia.register_all("hades_core:brick_dark_green", S("Dark Green Brick"))
columnia.register_all("hades_core:brick_dark_grey", S("Grey Brick"))
columnia.register_all("hades_core:brick_green", S("Green Brick"))
columnia.register_all("hades_core:brick_grey", S("Grey Brick"))
columnia.register_all("hades_core:brick_magenta", S("Magenta Brick"))
columnia.register_all("hades_core:brick_orange", S("Orange Brick"))
columnia.register_all("hades_core:brick_pink", S("Pink Brick"))
columnia.register_all("hades_core:brick_red", S("Red Brick"))
columnia.register_all("hades_core:brick_violet", S("Violet Brick"))
columnia.register_all("hades_core:brick_white", S("White Brick"))
columnia.register_all("hades_core:brick_yellow", S("Yellow Brick"))

columnia.register_all("hades_core:marble_brick")
columnia.register_all("hades_core:marble")
columnia.register_all("hades_core:chondrite")
columnia.register_all("hades_core:chondrite_brick")
columnia.register_all("hades_core:tuff")
columnia.register_all("hades_core:tuff_brick")
columnia.register_all("hades_core:tuff_baked")
columnia.register_all("hades_core:tuff_baked_brick")
columnia.register_all("hades_core:essexite")
columnia.register_all("hades_core:essexite_brick")

columnia.register_all("columnia:rusty_block")
