 --[[ 
 columnia.register_all   (
	mat, 
	desc, 
	image, 
	groups, 
	craft, 
	sounds
	)
	--]]

columnia.register_all("hades_core:sandstone")
columnia.register_all("hades_core:sandstonebrick")
columnia.register_all("hades_core:cobble")
columnia.register_all("hades_core:cobble_baked")
columnia.register_all("hades_core:stone")
columnia.register_all("hades_core:cactus", nil, "default_cactus_side.png")
columnia.register_all("hades_core:cactus_block")
columnia.register_all("hades_core:cactus_brick")
columnia.register_all("hades_core:stone_baked")
columnia.register_all("hades_core:stonebrick_baked")
columnia.register_all("hades_core:mossycobble")
columnia.register_all("hades_core:obsidian")
columnia.register_all("hades_core:obsidianbrick")
columnia.register_all("hades_core:sandstonebrick")
columnia.register_all("hades_core:stonebrick")

columnia.register_all("hades_trees:wood", "Common Wood")
columnia.register_all("hades_trees:jungle_wood", "Jungle Wood")
columnia.register_all("hades_trees:pale_wood", "Pale Wood")
columnia.register_all("hades_trees:birch_wood", "Birch Wood")
columnia.register_all("hades_trees:colwood_black", "Black Wood")
columnia.register_all("hades_trees:colwood_blue", "Blue Wood")
columnia.register_all("hades_trees:colwood_brown", "Brown Wood")
columnia.register_all("hades_trees:colwood_cyan", "Cyan Wood")
columnia.register_all("hades_trees:colwood_dark_green", "Dark Green Wood")
columnia.register_all("hades_trees:colwood_dark_grey", "Dark Grey Wood")
columnia.register_all("hades_trees:colwood_grey", "Grey Wood")
columnia.register_all("hades_trees:colwood_green", "Green Wood")
columnia.register_all("hades_trees:colwood_magenta", "Magenta Wood")
columnia.register_all("hades_trees:colwood_orange", "Orange Wood")
columnia.register_all("hades_trees:colwood_pink", "Pink Wood")
columnia.register_all("hades_trees:colwood_red", "Red Wood")
columnia.register_all("hades_trees:colwood_violet", "Violet Wood")
columnia.register_all("hades_trees:colwood_white", "White Wood")
columnia.register_all("hades_trees:colwood_yellow", "Yellow Wood")

columnia.register_all("hades_trees:bark")
columnia.register_all("hades_trees:jungle_bark")
columnia.register_all("hades_trees:pale_bark")
columnia.register_all("hades_trees:birch_bark")

columnia.register_all("hades_core:brick", "Brick")
columnia.register_all("hades_core:brick_black", "Black Brick")
columnia.register_all("hades_core:brick_blue", "Blue Brick")
columnia.register_all("hades_core:brick_brown", "Brown Brick")
columnia.register_all("hades_core:brick_cyan", "Cyan Brick")
columnia.register_all("hades_core:brick_dark_green", "Dark Green Brick")
columnia.register_all("hades_core:brick_dark_grey", "Grey Brick")
columnia.register_all("hades_core:brick_green", "Green Brick")
columnia.register_all("hades_core:brick_grey", "Grey Brick")
columnia.register_all("hades_core:brick_magenta", "Magenta Brick")
columnia.register_all("hades_core:brick_orange", "Orange Brick")
columnia.register_all("hades_core:brick_pink", "Pink Brick")
columnia.register_all("hades_core:brick_red", "Red Brick")
columnia.register_all("hades_core:brick_violet", "Violet Brick")
columnia.register_all("hades_core:brick_white", "White Brick")
columnia.register_all("hades_core:brick_yellow", "Yellow Brick")

columnia.register_all("hades_core:marble_brick")
columnia.register_all("hades_core:marble")
columnia.register_all("hades_core:chondrite")
columnia.register_all("hades_core:chondrite_brick")
columnia.register_all("hades_core:tuff")
columnia.register_all("hades_core:tuff_brick")
columnia.register_all("hades_core:tuff_baked")
columnia.register_all("hades_core:tuff_baked_brick")
columnia.register_all("hades_core:essexite")
columnia.register_all("hades_core:essexite_brick")

columnia.register_all("columnia:rusty_block")
