minetest.register_alias("default:mese_block", "default:mese")
minetest.register_alias("default:lamp_ceiling", "default:lamp_wall")
minetest.register_alias("default:lamp_stair", "default:lamp_wall")
minetest.register_alias("default:nyancat", "default:diamondblock")
minetest.register_alias("default:nyancat_rainbow", "default:goldblock")
